### ISSUE TITLE
archive project

### ISSUE THREAD

**Issue by DanielRuf** [WPOTools/perfBar#28]

**Comment by DanielRuf** [comment]
Also the URL http://wpotools.github.io/perfBar/ is not valid anymore.

**Comment by DanielRuf** [comment]
Bump.

**Comment by lafikl** [comment]
Why would i archivd the project?

**Comment by DanielRuf** [comment]
The issue is the very outdated code, low mainrainment, non working links and so on.

**Comment by DanielRuf** [comment]
The issue is the very outdated code, low maintainment, non working links and so on.

**Comment by DanielRuf** [comment]
Also Bower is dead and the dependencies are a bit outdated.
